# === Base Colors ===
background            #060B1E
foreground            #ffcead
cursor                #ffcead

selection_background  #ffcead
selection_foreground  #060B1E

# === ANSI Colors ===
color0  #060B1E
color1  #ED5B5A
color2  #92a593
color3  #E9BB4F
color4  #7d82d9
color5  #c89dc1
color6  #a3bfd1
color7  #F99957

color8  #6d7db6
color9  #faaaa9
color10 #c4cfc4
color11 #f7dc9c
color12 #c2c4f0
color13 #ead7e7
color14 #dfeaf0
color15 #ffcead

# Cursor
cursor                #f5e0dc
cursor_text_color     #0f0f17

# URL underline
url_color             #89b4fa

# Tab bar
tab_bar_style powerline
tab_fade 1
active_tab_foreground   #11111b
active_tab_background   #cba6f7
active_tab_font_style   bold
inactive_tab_foreground #cdd6f4
inactive_tab_background #0f0f17
inactive_tab_font_style bold
tab_bar_background      #0f0f17

